function grad_h_vo = grad_h_vo_fun(in1,in2,theta,v,in5,in6,R_A,R_B,alpha_vo)
%GRAD_H_VO_FUN
%    GRAD_H_VO = GRAD_H_VO_FUN(IN1,IN2,THETA,V,IN5,IN6,R_A,R_B,ALPHA_VO)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Mar-2025 10:58:32

p_A1 = in1(1,:);
p_A2 = in1(2,:);
p_B1 = in2(1,:);
p_B2 = in2(2,:);
v_B1 = in5(1,:);
v_B2 = in5(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = R_A+R_B;
t7 = -p_B1;
t8 = -p_B2;
t5 = t2.*v;
t6 = t3.*v;
t9 = t4.^2;
t10 = p_A1+t7;
t11 = p_A2+t8;
t12 = -t5;
t13 = -t6;
t14 = -t9;
t15 = t10.^2;
t16 = t11.^2;
t17 = t14+t15+t16;
t18 = t12+v_B1+2.220446049250313e-16;
t19 = t13+v_B2+2.220446049250313e-16;
t20 = t18.^2;
t21 = t19.^2;
t22 = sqrt(t17);
t23 = conj(t22);
t25 = t20+t21;
t24 = 1.0./t23;
t26 = sqrt(t25);
t27 = 1.0./t26;
grad_h_vo = [t5-v_B1+(t24.*t26.*(p_A1.*2.0-p_B1.*2.0))./2.0-2.220446049250313e-16;t6-v_B2+(t24.*t26.*(p_A2.*2.0-p_B2.*2.0))./2.0-2.220446049250313e-16;t5.*t11+t10.*t13-(t23.*t27.*(t5.*t19.*2.0-t6.*t18.*2.0))./2.0;t2.*t10+t3.*t11-(t23.*t27.*(t2.*t18.*2.0+t3.*t19.*2.0))./2.0];
end
