function h_scbf = h_scbf_fun(in1,in2,theta,v,in5,in6,u_max,delta,alpha_c)
%H_SCBF_FUN
%    H_SCBF = H_SCBF_FUN(IN1,IN2,THETA,V,IN5,IN6,U_MAX,DELTA,ALPHA_C)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Mar-2025 11:02:01

p_A1 = in1(1,:);
p_A2 = in1(2,:);
p_B1 = in2(1,:);
p_B2 = in2(2,:);
v_B1 = in5(1,:);
v_B2 = in5(2,:);
t2 = -p_B1;
t3 = -p_B2;
t4 = p_A1+t2;
t5 = p_A2+t3;
t6 = t4.^2;
t7 = t5.^2;
t8 = t6+t7;
t9 = 1.0./sqrt(t8);
h_scbf = -delta-(t4.*t9.*(v_B1-v.*cos(theta)+2.220446049250313e-16)+t5.*t9.*(v_B2-v.*sin(theta)+2.220446049250313e-16)).^2./(u_max.*2.0)+1.0./t9;
end
