function h_vo = h_vo_fun(in1,in2,theta,v,in5,in6,R_A,R_B,alpha_vo)
%H_VO_FUN
%    H_VO = H_VO_FUN(IN1,IN2,THETA,V,IN5,IN6,R_A,R_B,ALPHA_VO)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Mar-2025 10:58:32

p_A1 = in1(1,:);
p_A2 = in1(2,:);
p_B1 = in2(1,:);
p_B2 = in2(2,:);
v_B1 = in5(1,:);
v_B2 = in5(2,:);
t2 = cos(theta);
t3 = sin(theta);
t6 = -p_B1;
t7 = -p_B2;
t4 = t2.*v;
t5 = t3.*v;
t8 = p_A1+t6;
t9 = p_A2+t7;
t10 = -t4;
t11 = -t5;
t12 = t10+v_B1+2.220446049250313e-16;
t13 = t11+v_B2+2.220446049250313e-16;
h_vo = -t8.*t12-t9.*t13+sqrt(t12.^2+t13.^2).*sqrt(-(R_A+R_B).^2+t8.^2+t9.^2);
end
