function h_scbf = h_scbf_fun(in1,in2,in3,in4,in5,u_max,delta,alpha_c)
%H_SCBF_FUN
%    H_SCBF = H_SCBF_FUN(IN1,IN2,IN3,IN4,IN5,U_MAX,DELTA,ALPHA_C)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    28-Feb-2025 13:10:05

p_A1 = in1(1,:);
p_A2 = in1(2,:);
p_B1 = in2(1,:);
p_B2 = in2(2,:);
v_A1 = in3(1,:);
v_A2 = in3(2,:);
v_B1 = in4(1,:);
v_B2 = in4(2,:);
t2 = -p_B1;
t3 = -p_B2;
t4 = p_A1+t2;
t5 = p_A2+t3;
t6 = t4.^2;
t7 = t5.^2;
t8 = t6+t7;
t9 = 1.0./sqrt(t8);
h_scbf = -delta+1.0./t9-(t4.*t9.*(-v_A1+v_B1+2.220446049250313e-16)+t5.*t9.*(-v_A2+v_B2+2.220446049250313e-16)).^2./(u_max.*2.0);
end
