function h_vo = h_vo_fun(in1,in2,in3,in4,in5,R_A,R_B,alpha_vo)
%H_VO_FUN
%    H_VO = H_VO_FUN(IN1,IN2,IN3,IN4,IN5,R_A,R_B,ALPHA_VO)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    28-Feb-2025 13:10:04

p_A1 = in1(1,:);
p_A2 = in1(2,:);
p_B1 = in2(1,:);
p_B2 = in2(2,:);
v_A1 = in3(1,:);
v_A2 = in3(2,:);
v_B1 = in4(1,:);
v_B2 = in4(2,:);
t2 = -p_B1;
t3 = -p_B2;
t4 = -v_A1;
t5 = -v_A2;
t6 = p_A1+t2;
t7 = p_A2+t3;
t8 = t4+v_B1+2.220446049250313e-16;
t9 = t5+v_B2+2.220446049250313e-16;
h_vo = -t6.*t8-t7.*t9+sqrt(t8.^2+t9.^2).*sqrt(-(R_A+R_B).^2+t6.^2+t7.^2);
end
